#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2018111500
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=723570

mkdir /stmpp1/Alicia.Bentley/MEG
mkdir /stmpp1/Alicia.Bentley/MEG/snd
rm /stmpp1/Alicia.Bentley/MEG/snd/*
cd /stmpp1/Alicia.Bentley/MEG/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold7

DAPATH=/com2/nawips/prod/nam.${ymd}
DAPATH=/meso/noscrub/Geoffrey.Manikin/hold
fmdl1=${DAPATH}/nam_${ymdh}.snd.tm00
fmdl2=${DAPATH}/nam_conusnest_${ymdh}.snd.tm00

times="00 06"
#times="00 03 06 09 12 15 18"
for time in $times; do

validtime="`/meso/save/Alicia.Bentley/MEG/soundings/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/6
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM 
 DEVICE   = gif|nam_nest_${stnm}_${ymdh}f$fhr.gif | 800;850
 YAXIS    = 1000/400/50/1;1;1
 XAXIS    = -25/25/5/;1
 FILTER   = 0.9 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//  NAM3
 PANEL    = b
r

ex
EOF

done
gpend

scp *gif abentley@emcrzdm:/home/people/emc/www/htdocs/users/Alicia.Bentley/MEG/soundings/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/${ymd}/.
exit
