#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2018111512
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=723570
#stnm=744550

mkdir /stmpp1/Alicia.Bentley/MEG
mkdir /stmpp1/Alicia.Bentley/MEG/snd
rm /stmpp1/Alicia.Bentley/MEG/snd/*
cd /stmpp1/Alicia.Bentley/MEG/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold

fmdl1=/com2/nawips/prod/nam.${ymd}/nam_${ymdh}.snd.tm00
fmdl2=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/nawips/rap_${ymdh}.snd
#fmdl2=/ptmpp1/Geoffrey.Manikin/test2/rap13_${ymdh}.snd

times="00 03 06 07 08 09 12"
times="00 03 06 09 12"
times="00 01 02 03 04 05 06 07 08 09 10 11 12"
for time in $times; do

validtime="`/meso/save/Alicia.Bentley/MEG/soundings/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins;lclp
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM 
 DEVICE   = gif|${ymdh}snd${stnm}_namrap$fhr.gif | 800;850
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -25/25/5/;1
 FILTER   = no 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//  RAP 
 PANEL    = b
r

ex
EOF

done
gpend
scp *gif abentley@emcrzdm:/home/people/emc/www/htdocs/users/Alicia.Bentley/MEG/soundings/.
exit
