#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

unit=$1
mdlymdh=$2

mdlymd=`echo $mdlymdh | cut -c1-8`
#stations="727970 726940 725970 724930 723930 722930 723860=723880 724890 725820 726810 727860 727760=727750 727680 725765=726720 725720 723760 722740 724760 724690 723650 723640 722500 722510 722610 722650 723630 722490 723570 724510 724560 725620 725580 726620 726590 727640 727470 726490 724400 723400 722480 722400 722330 722350 722300 723270 745600 744550 726450 726340 726320 724260 722150 727120 743890 744940 725180 725280 725200 725010 724030 724020 723180 723170 723050 722080 722060 722140 747940 722100 722020 722010 911650 912850 785260 703980 703610 703500 703260 702730 703080 702190 702610 701330 703160 702000"
#stations="726490 727750=727760"

cd /stmpp1/Alicia.Bentley/gempak.sound/phys${unit}
cp /meso/save/Alicia.Bentley/phys/coltbl.xwp .

DAPATH=/meso/noscrub/Alicia.Bentley/phys/
fmdl1=${DAPATH}/suite1_${mdlymdh}.snd
fmdl2=${DAPATH}/suite2_${mdlymdh}.snd
fmdl3=${DAPATH}/suite3_${mdlymdh}.snd
fmdl4=${DAPATH}/suite4_${mdlymdh}.snd
echo $fmdl1
echo $mdlymdh

counter=0
times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 999"
for time in $times; do

file_name=input_list_${unit}
cp /meso/save/Alicia.Bentley/phys/$file_name /stmpp1/Alicia.Bentley/gempak.sound/phys${unit}/$file_name 

nlines=`cat $file_name | wc -l`
line=0

while [ $line -lt $nlines ]
do 

  line=`expr $line + 1`    
  station=`awk 'NR==j{print $0}' j=$line $file_name`

stnnum=`echo $station | cut -d= -f1`
stnnm=`echo $station | cut -d= -f2`
echo $stnnum
echo $stnnm
stn=`echo $stnnm | cut -c1-5`
echo 'final'
echo $stn

if test "$stnnum" = "done" 
then
if test "$time" = "999"
then
gpend
counting="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24"
for count in $counting; do

nlines=`cat $file_name | wc -l`
line=0

while [ $line -lt $nlines ]
do

line=`expr $line + 1`
station=`awk 'NR==j{print $0}' j=$line $file_name`

stnnum=`echo $station | cut -d= -f1`
stnnm=`echo $station | cut -d= -f2`
stn2=`echo $stnnm | cut -c1-5`
stn=`expr $stn2 \* 10`

ls
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 ${stn2}_stream12_${count}.gif ${stn}_${count}_1.gif
$CONV/convert -crop 0x0 ${stn2}_stream34_${count}.gif ${stn}_${count}_2.gif
$CONV/montage -geometry 800x850 ${stn}_${count}_1.gif ${stn}_${count}_2.gif ${mdlymdh}_${stn}_${count}.gif
done
done

mv ${mdlymdh}*gif /stmpp1/Alicia.Bentley/gempak.sound/hold/.
exit
fi
fi
               
dattim="`/meso/save/Geoffrey.Manikin/meg/advtime ${mdlymdh} $time -1 x`"
validtime=`echo $dattim | cut -c1-11`
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c10-11`
fobs=/dcom/us007003/ldmdata/gempak/uair/$ymd.snd
#fobs=/ptmpd2/Alicia.Bentley/com2/nawips/prod/obs/snd/$ymd.snd

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $ymd/$cyc
 AREA     = @${stnnum}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = capv;cinv;lclp
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  SUITE1 DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|${stn}_stream12_${counter}.gif|1000;1000
 YAXIS    = 1050/500/50/1;1;1
 XAXIS    = -25/30/5/;1
 FILTER   = 0.8
 CLEAR    = y
 PANEL    = t
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fobs
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/5 
 AREA     = @${stn}
r

 SNFILE   = $fmdl2
 WINPOS   = 2
 LINE     = 2;4/2/7
 AREA     = @${stnnum}
 TITLE    = 1//  SUITE2 DASHED   OBS SOLID/LEFT WINDS
 PANEL    = b
r

 SNFILE   = $fobs
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/5
 AREA     = @${stn}
r

 SNFILE   = $fmdl3
 WINPOS   = 2
 LINE     = 2;4/2/7
 AREA     = @${stnnum}
 CLEAR    = y
 DEVICE   = gif|${stn}_stream34_${counter}.gif|1000;1000
 TITLE    = 1//  SUITE3 DASHED   OBS SOLID/LEFT WINDS
 PANEL    = t
r

 SNFILE   = $fobs
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/5
 AREA     = @${stn}
r

 SNFILE   = $fmdl4
 WINPOS   = 2
 LINE     = 2;4/2/7
 AREA     = @${stnnum}
 TITLE    = 1//  SUITE4 DASHED   OBS SOLID/LEFT WINDS
 PANEL    = b
r

 SNFILE   = $fobs
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/5
 AREA     = @${stn}
r

ex
EOF

done
counter=`expr $counter + 1`
done
gpend
exit
